/// @description Draw the disk
switch(mySize) {
case(0):
draw_set_color(obj_data.colorTheme1);
draw_circle(x,y,obj_data.sizeZero,0);
draw_set_color(c_white);
draw_circle(x,y,obj_data.sizeZero,1);
draw_circle(x,y,obj_data.sizeZero-1,1);
draw_circle(x,y,obj_data.sizeZero-2,1);
break;
case(1):
draw_set_color(obj_data.colorTheme2);
draw_circle(x,y,obj_data.sizeOne,0);
draw_set_color(c_white);
draw_circle(x,y,obj_data.sizeOne,1);
draw_circle(x,y,obj_data.sizeOne-1,1);
draw_circle(x,y,obj_data.sizeOne-2,1);
break;
case(2):
draw_set_color(obj_data.colorTheme3);
draw_circle(x,y,obj_data.sizeTwo,0);
draw_set_color(c_white);
draw_circle(x,y,obj_data.sizeTwo,1);
draw_circle(x,y,obj_data.sizeTwo-1,1);
draw_circle(x,y,obj_data.sizeTwo-2,1);
break;
case(3):
draw_set_color(obj_data.colorTheme1);
draw_circle(x,y,obj_data.sizeThree,0);
draw_set_color(c_white);
draw_circle(x,y,obj_data.sizeThree,1);
draw_circle(x,y,obj_data.sizeThree-1,1);
draw_circle(x,y,obj_data.sizeThree-2,1);
break;
case(4):
draw_set_color(obj_data.colorTheme2);
draw_circle(x,y,obj_data.sizeFour,0);
draw_set_color(c_white);
draw_circle(x,y,obj_data.sizeFour,1);
draw_circle(x,y,obj_data.sizeFour-1,1);
draw_circle(x,y,obj_data.sizeFour-2,1);
break;
case(5):
draw_set_color(obj_data.colorTheme3);
draw_circle(x,y,obj_data.sizeFive,0);
draw_set_color(c_white);
draw_circle(x,y,obj_data.sizeFive,1);
draw_circle(x,y,obj_data.sizeFive-1,1);
draw_circle(x,y,obj_data.sizeFive-2,1);
break;
case(6):
draw_set_color(obj_data.colorTheme1);
draw_circle(x,y,obj_data.sizeSix,0);
draw_set_color(c_white);
draw_circle(x,y,obj_data.sizeSix,1);
draw_circle(x,y,obj_data.sizeSix-1,1);
draw_circle(x,y,obj_data.sizeSix-2,1);
break;
case(7):
draw_set_color(obj_data.colorTheme2);
draw_circle(x,y,obj_data.sizeSeven,0);
draw_set_color(c_white);
draw_circle(x,y,obj_data.sizeSeven,1);
draw_circle(x,y,obj_data.sizeSeven-1,1);
draw_circle(x,y,obj_data.sizeSeven-2,1);
break;
case(8):
draw_set_color(obj_data.colorTheme3);
draw_circle(x,y,obj_data.sizeEight,0);
draw_set_color(c_white);
draw_circle(x,y,obj_data.sizeEight,1);
draw_circle(x,y,obj_data.sizeEight-1,1);
draw_circle(x,y,obj_data.sizeEight-2,1);
break;
case(9):
draw_set_color(obj_data.colorTheme1);
draw_circle(x,y,obj_data.sizeNine,0);
draw_set_color(c_white);
draw_circle(x,y,obj_data.sizeNine,1);
draw_circle(x,y,obj_data.sizeNine-1,1);
draw_circle(x,y,obj_data.sizeNine-2,1);
break;
case(10):
draw_set_color(obj_data.colorTheme2);
draw_circle(x,y,obj_data.sizeTen,0);
draw_set_color(c_white);
draw_circle(x,y,obj_data.sizeTen,1);
draw_circle(x,y,obj_data.sizeTen-1,1);
draw_circle(x,y,obj_data.sizeTen-2,1);
break;
}