/// @description Draw the disk
draw_set_color(myColor);
draw_set_circle_precision(240);
switch(mySize) {
case(0):
draw_set_color(obj_data.colorZero);
draw_circle(x,y,obj_data.sizeZero,0);
break;
case(1):
draw_set_color(obj_data.colorOne);
draw_circle(x,y,obj_data.sizeOne,0);
break;
case(2):
draw_set_color(obj_data.colorTwo);
draw_circle(x,y,obj_data.sizeTwo,0);
break;
case(3):
draw_set_color(obj_data.colorThree);
draw_circle(x,y,obj_data.sizeThree,0);
break;
case(4):
draw_set_color(obj_data.colorFour);
draw_circle(x,y,obj_data.sizeFour,0);
break;
case(5):
draw_set_color(obj_data.colorFive);
draw_circle(x,y,obj_data.sizeFive,0);
break;
case(6):
draw_set_color(obj_data.colorSix);
draw_circle(x,y,obj_data.sizeSix,0);
break;
case(7):
draw_set_color(obj_data.colorSeven);
draw_circle(x,y,obj_data.sizeSeven,0);
break;
case(8):
draw_set_color(obj_data.colorEight);
draw_circle(x,y,obj_data.sizeEight,0);
break;
case(9):
draw_set_color(obj_data.colorNine);
draw_circle(x,y,obj_data.sizeNine,0);
break;
case(10):
draw_set_color(obj_data.colorTen);
draw_circle(x,y,obj_dataController.sizeTen,0);
break;
}